#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
MARIADB_DATABASE = data.get("MARIADB_DATABASE", "postal") 
MARIADB_ALLOW_EMPTY_PASSWORD = data.get("MARIADB_ALLOW_EMPTY_PASSWORD", "yes") 
MARIADB_ALLOW_EMPTY_ROOT_PASSWORD = data.get("MARIADB_ALLOW_EMPTY_ROOT_PASSWORD", "yes") 
 
mariadb = { 
 "MARIADB_DATABASE" : MARIADB_DATABASE ,
 "MARIADB_ALLOW_EMPTY_PASSWORD" : MARIADB_ALLOW_EMPTY_PASSWORD ,
 "MARIADB_ALLOW_EMPTY_ROOT_PASSWORD" : MARIADB_ALLOW_EMPTY_ROOT_PASSWORD ,
} 
agent.write_envfile("mariadb.env", mariadb) 
